# ===============================================================
# Improve your site configuration according to the following 
# configuration instructions. It is recommended to make 
# additional copies for adjustment to avoid conflicts
# ===============================================================

# ---------------------------------------------------------------
# Basic configure for Hugo engine 
# ---------------------------------------------------------------

# Website domain, eg: https://ego.systemdef.com 
baseURL: /
# Website title
title: Ego
# Theme name
theme: hugo-theme-next
# Default laguage & code for website
defaultContentLanguage: en
languageCode: English
# Whether contains Chinese, Japanese and Korean
hasCJKLanguage: false
# Display items per page
paginate: 100
# Enable Emoji support
enableEmoji: true
# Make markdown content support HTML syntax, highlight, toc etc.
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # codeFences: true
    # lineNos: true
    # lineNumbersInTable: true
    # noClasses: true
    # # Highlight style: monokai | emacs | api | dracula | friendly
    # # More: https://xyproto.github.io/splash/docs/all.html 
    style: monokai
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    tabWidth: 2
  tableOfContents:
    # Heading title level of start or end: 1-6
    # Recommand start at 2
    startLevel: 2
    endLevel: 4

# Site map of all articles
sitemap:
  filename: "sitemap.xml"
  changefreq: "weekly"
  priority: 0.5

outputFormats:
  RSS:
    baseName: "rss"
  # Custom file of indexes for local search
  LocalIndexes:
    mediaType: application/xml
    baseName: searchindexes
    isPlainText: true
    notAlternative: true
  # Build indexes of Aloglia
  AlgoliaIndexes:
    mediaType: application/json
    baseName: algolia
    isPlainText: true
    notAlternative: true

# Algolia，LocalIndexes
# By default use local search, before switch to Algolia engine
# Please replace LocalIndexes with AlgoliaIndexes
outputs:
  home: ["HTML", "RSS", "LocalIndexes"]

# Enable robots with support crawler scan
enableRobotsTXT: true

# Compress all files when output
minify:
  minifyOutput: true

