#--------------------------------------
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------

main:
  - identifier: home
    name: Home
    pageref: /
    pre: home
    weight: 1

  - identifier: engineering
    name: Engineering
    pageref: /categories/engineering/
    pre: gear
    weight: 2

  - identifier: books
    name: My library
    pageref: /categories/books/
    pre: book
    weight: 3

  - identifier: tabs
    name: My tabs
    pageref: /categories/tabs/
    pre: bookmark
    weight: 4

  - identifier: courses
    name: Courses
    pageref: /categories/courses/
    pre: graduation-cap
    weight: 5

  # - identifier: writings
  #   name: Writings
  #   pageref: /categories/writings/
  #   pre: pen
  #   weight: 6

  - identifier: categories
    name: Categories
    pageref: /categories
    pre: list
    weight: 7

  - identifier: archives
    name: Timeline
    pageref: /archives.html
    pre: timeline
    weight: 8

  - identifier: tags
    name: Tags
    pageref: /tags/
    pre: tags
    weight: 9

  - identifier: about
    name: About
    pageref: /about.html
    pre: user
    weight: 10

  - identifier: flinks
    name: Friends
    pageref: /flinks.html
    pre: thumbs-up
    weight: 11
