#--------------------------------------
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------

main:
  - identifier: home
    name: Home
    pageref: /
    pre: home
    weight: 1

  - identifier: about
    name: About
    pageref: /about.html
    pre: user
    weight: 2

  - identifier: engineering
    name: Engineering
    pageref: /categories/engineering/
    pre: gear
    weight: 3

  - identifier: ai
    name: Artificial Intelligence
    pageref: /categories/ai/
    pre: brain
    weight: 4

  - identifier: open-source
    name: Open source
    pageref: /categories/open-source/
    pre: users
    weight: 5

  - identifier: projects
    name: My Projects
    pageref: /categories/projects/
    pre: user-shield
    weight: 6

  - identifier: tabs
    name: My tabs
    pageref: /categories/tabs/
    pre: bookmark
    weight: 7

  - identifier: books
    name: My library
    pageref: /categories/books/
    pre: book
    weight: 8

  - identifier: courses
    name: Courses
    pageref: /categories/courses/
    pre: graduation-cap
    weight: 9

  - identifier: notes
    name: Notes
    pageref: /categories/note/
    pre: pen
    weight: 10

  # - identifier: writings
  #   name: Writings
  #   pageref: /categories/writings/
  #   pre: pen
  #   weight: 11

  - identifier: categories
    name: Categories
    pageref: /categories
    pre: list
    weight: 12

  - identifier: archives
    name: Timeline
    pageref: /archives.html
    pre: timeline
    weight: 13

  - identifier: tags
    name: Tags
    pageref: /tags/
    pre: tags
    weight: 14

  - identifier: flinks
    name: Friends
    pageref: /flinks.html
    pre: thumbs-up
    weight: 15

  - identifier: blogs
    name: Blogs
    pageref: /post/engineering/blogs.html
    pre: rss
    weight: 16
