#--------------------------------------
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------

main:
  - identifier: home
    name: Home
    pageref: /
    pre: home
    weight: 1

  - identifier: engineering
    name: Engineering
    pageref: /about.html
    pre: gear
    weight: 2

  # - identifier: writings
  #   name: Writings
  #   pageref: /about.html
  #   pre: pen
  #   weight: 3

  # - identifier: categories
  #   name: Categories
  #   pageref: /categories
  #   pre: list
  #   weight: 4

  # - identifier: books
  #   name: Books
  #   pageref: /books.html
  #   pre: book
  #   weight: 5

  # - identifier: Courses
  #   name: Courses
  #   pageref: /course.html
  #   pre: graduation-cap
  #   weight: 6

  # - identifier: about
  #   name: About
  #   pageref: /about.html
  #   pre: user
  #   weight: 7

  # - identifier: flinks
  #   name: Friends
  #   pageref: /flinks.html
  #   pre: thumbs-up
  #   weight: 8
